language: node_js
node_js:
  - 0.6
  - 0.9
git:
  depth: 1
branches:
  only:
    - master
before_script:
  - "tar -xzvf vendor/closure-compiler.tar.gz -C vendor"
  - "tar -xzvf vendor/uglifyjs.tar.gz -C vendor"
