language: node_js
node_js:
  - 0.6
  - 0.9
env:
  - TEST_COMMAND="node ./test/test.js ./dist/lodash.js"
  - TEST_COMMAND="node ./test/test.js ./dist/lodash.min.js"
  - TEST_COMMAND="node ./test/test-build.js --time-limit 49m40s"
git:
  depth: 1
branches:
  only:
    - master
before_script:
  - "tar -xzvf vendor/closure-compiler.tar.gz -C vendor"
  - "tar -xzvf vendor/uglifyjs.tar.gz -C vendor"
script:
  $TEST_COMMAND
